export const MockFilterOptions = [
  'Addresses',
  'Bank Accounts',
  'Crypto Wallets',
  'Individuals',
  'Legal Entities',
  'Securities',
  'Aircrafts or Ships'
]

export const entityCreateDisplayOption = ['Public', 'Draft', 'Private']

export const entityCreateDatasetType = ['non-official source', 'external dataset']

export const dedicatedRenderArray = ['Type', 'Name', 'Other name', 'Source link', 'Topics', 'Website', 'Phone', 'Wikidata ID', 'Notes text', 'LEI', 'OpenCorporates URL', 'E-Mail', 'Country', 'Nationality', 'Jurisdiction', 'Issuer', 'Wallet holder', 'Created at', 'Modified on', 'Last seen', 'First seen', 'Last change', 'Entity address', 'Country of birth']

export const mockAdminAnalyticsSortByYear = ['This Month', 'This Day']

export const mockSortOptions = [
  'Oldest Updated',
  'Most Relevant'
]

export const mockSpecialFilterTags = [
  'Political',
  'Debarred entity',
  'Sanctioned entity',
  'Close Associate',
  'Offshore',
  'Theft',
  'Crime',
  'State-owned enterprise',
  'Financial crime',
  'Diplomat',
  'War crimes',
  'Bank',
  'Judge',
  'Military',
  'Terrorism',
  'Person of interest',
  'Oligarch',
  'Trafficking',
  'Political party',
  'Spy',
  'Intergovernmental organization',
  'Criminal leadership'
]

export const mockCountryFilter = [
  'Afghanistan',
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, The Democratic Republic of the',
  'Cook Islands',
  'Costa Rica',
  'Cote D\'Ivoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and Mcdonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Republic Of',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, Democratic People\'S Republic of',
  'Korea, Republic of',
  'Kuwait',
  'Kyrgyzstan',
  'Lao People\'S Democratic Republic',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia, The Former Yugoslav Republic of',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States of',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territory, Occupied',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province of China',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Virgin Islands, British',
  'Virgin Islands, U.S.',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Yugoslavia',
  'Serbia and Montenegro',
  'Czechoslovakia',
  'Soviet Union',
  'Abkhazia (Occupied Georgia)',
  'South Ossetia (Occupied Georgia)',
  'Luhansk (Occupied Ukraine)',
  'Donetsk (Occupied Ukraine)',
  'Crimea (Occupied Ukraine)',
  'Somaliland',
  'Northern Cyprus',
  'Nagorno-Karabakh',
  'Tibet',
  'Sark',
  'Wales',
  'Scotland',
  'Northern Ireland',
  'Transnistria (PMR)'
]

export const allCountriesList = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: 'Cote D\'Ivoire', code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: 'Korea', code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: 'Lao People\'S Democratic Republic', code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia', code: 'FM' },
  { name: 'Moldova', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia and Montenegro', code: 'CS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
  { code: 'YUCS', name: 'Yugoslavia' },
  { code: 'CSXX', name: 'Serbia and Montenegro' },
  { code: 'CSHH', name: 'Czechoslovakia' },
  { code: 'SUHH', name: 'Soviet Union' },
  { code: 'GE-AB', name: 'Abkhazia (Occupied Georgia)' },
  { code: 'X-SO', name: 'South Ossetia (Occupied Georgia)' },
  { code: 'UA-LPR', name: 'Luhansk (Occupied Ukraine)' },
  { code: 'UA-DPR', name: 'Donetsk (Occupied Ukraine)' },
  { code: 'UA-CRI', name: 'Crimea (Occupied Ukraine)' },
  { code: 'SO-SOM', name: 'Somaliland' },
  { code: 'CY-TRNC', name: 'Northern Cyprus' },
  { code: 'AZ-NK', name: 'Nagorno-Karabakh' },
  { code: 'CN-XZ', name: 'Tibet' },
  { code: 'GG-SRK', name: 'Sark' },
  { code: 'GB-WLS', name: 'Wales' },
  { code: 'GB-SCT', name: 'Scotland' },
  { code: 'GB-NIR', name: 'Northern Ireland' },
  { code: 'MD-PMR', name: 'Transnistria (PMR)' }
]

export const mockButtonCategory = ['Address', 'Vessels', 'Bank Account', 'Company', 'Crypto Wallet', 'Person', 'Security']

export const mockDetailsArray = [
  {
    country: 'code or src',
    name: 'VINER-USMANOVA Irina Aleksandrovna',
    tags: ['Close Associate', 'Sanctioned entity'],
    isSanctions: 'VINER-USMANOVA Irina Aleksandrovna is subject to sanctions. See the individual program listings below.',
    date: '30 May, 2023',
    type: 'Person',
    factsheet: {
      Name: 'VINER-USMANOVA Irina Aleksandrovna',
      'Other name': 'Irina Aleksandrovna Viner-Usmanova - Irina Viner-Usmanova',
      'Birth date': '1948-07-30',
      'Place of birth': 'Jamaica Hospital Medical Center',
      Gender: 'Female',
      Nationality: 'Russia · Soviet Union',
      Country: 'Russia · Uzbekistan',
      'First name': 'Irina · Ирина',
      Keywords: 'National government',
      'Last name': 'Trump',
      'Office Phone': '+1 (480) 555-0103',
      'Wikidata ID': 'Q2288379',
      Position: 'Government of Russia (member of the Council for the Development of Physical Culture and Mass Sports under the Government) · Usmanov`s wife, Alisher Burkhanovich, is a member of the supreme council of the United Russia party, president of the All-Russian public organization "All-Russian Federation of Rhythmic Gymnastics", Chairman of the Commission of the Public Chamber of the Russian Federation on Physical Culture and Promoting a Healthy Lifestyle · Дружина Усманова Алішера Бурхановича, входить до складу вищої ради партії "Єдина Росія", президент Загальноросійської громадської організації "Всеросійська федерація художньої гімнастики", Голова Комісії Громадської палати Російської Федерації з фізичної культури та популяризації здорового способу життя · Жена Усманова Алишера Бурхановича, входит в состав высшего совета партии "Единая Россия", президент Общероссийской общественной организации «Всероссийская федерация художественной гимнастики», Председатель Комиссии Общественной палаты Российской Федерации по физической культуре и популяризации здорового образа жизни · Правительство России (член совета по развитию физической культуры и массового спорта при правительстве)',
      Education: 'Doctor of Pedagogy Sciences',
      Status: 'Close associate',
      Religion: 'Presbyterianism',
      'Created at': '2022-10-13',
      'Modified on': '2023-08-06',
      'Source link': ['rupep.org', 'sanctions.nazk.gov.ua']
    },
    negative_media: [{
      title: 'Human rights abuses in Vietnam',
      outlet: 'Guardian',
      date: '18 Aug 2021',
      link: 'link'
    }, {
      title: 'Fabric company under investigation',
      outlet: 'Daily Mail',
      date: '15 Oct 2020',
      link: 'link'
    },
    {
      title: 'Are you sourcing ethically?',
      outlet: 'Times',
      date: '25 Sep 2020',
      link: 'link'
    },
    {
      title: 'Workers go on strike',
      outlet: 'Guardian',
      date: '3 May 2018',
      link: 'link'
    }],
    location_markers: [{
      coordinatesX: 'randomX'
    }, { coordinatesY: 'randomY' }],
    relationship: [{
      relative: 'Alisher USMANOV',
      relationship: 'Husband · Wife',
      startDate: '-',
      endDate: '-',
      link: 'link'
    }, {
      relative: 'Daniil Natanovich Viner',
      relationship: 'Grandmother · Grandson',
      startDate: '-',
      endDate: '-',
      link: 'link'
    },
    {
      relative: 'Alisher USMANOV',
      relationship: 'spouse',
      startDate: '1992',
      endDate: '-',
      link: 'link'
    },
    {
      relative: 'Boris Viner',
      relationship: 'Sibling',
      startDate: '-',
      endDate: '-',
      link: 'link'
    },
    {
      relative: 'Ivanka Trump',
      relationship: 'Child',
      startDate: '1992',
      endDate: '-',
      link: 'link'
    },
    {
      relative: 'Natan Adad`yevich Viner',
      relationship: 'Mother · Son',
      startDate: '-',
      endDate: '-',
      link: 'link'
    },
    {
      relative: 'Marla Maples',
      relationship: 'Spouse',
      startDate: '1993-12-20',
      endDate: '1999-06-08',
      link: 'link'
    }],
    sources: [{
      icon: '../assets/svg/google.svg',
      quantity: 987,
      tag: 'global',
      description: 'The ADB`s published sanctions list. It contains the names of entities who violated the sanctions while ineligible; entities…',
      place: 'Asian Development Bank',
      link: 'link'
    }, {}],
    description: 'Member of the Supreme Council of the United Russia party. United Russia forms and implements Vladimir Putin`s policy of aggression against territorial integrity, sovereignty and independence of Ukraine.'
  }
]

export const mockAdminStatusData = ['Approved', 'Reviewing', 'Denied']

export const mockAdminBulkUploadStatus = ['Failure', 'Success']

export const mockReportSelectOptions = ['Own entity', 'Customer', 'Supplier', 'Journalist', 'Other']

export const mockAdminEditingFields = [
  { svg: 'UserSVG', text: 'First Name', placeholder: 'First Name' },
  { svg: 'UserSVG', text: 'Last Name', placeholder: 'Last Name' },
  { svg: 'MailSVG', text: 'Email', placeholder: 'Email' },
  { svg: 'PhoneSVG', text: 'Phone', placeholder: 'Phone Number' },
  { svg: 'LinkSVG', text: 'Entity Name', placeholder: 'Entity Name' },
  { svg: 'ShareSVG', text: 'Relationship', placeholder: 'Relationship to data' }]

export const mockAdminEditInDetailsReviews =
  [{
    id: '1',
    name: 'Jenny Bilson',
    created_at: '08/06/2023',
    title: 'Lorem Ipsum is simply dummy text',
    subtitle: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'
  },
  {
    id: '2',
    name: 'Eleanor sena',
    created_at: '03/06/2023',
    title: 'The Walt Disney Company',
    subtitle: 'Walk Disney Company is making a funny movies for kids.'
  }]

export const mockAdminAnalyticsTable = [
  {
    name: 'Annette Glash',
    type: 'Basic Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '07:00 am'
  },
  {
    name: 'Kathryn Jurphy',
    type: 'Basic Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '06:30 pm'
  },
  {
    name: 'Jenny Bilson',
    type: 'Basic Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '06:00 pm'
  },
  {
    name: 'Eleanor sena',
    type: 'Basic Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '06:00 pm'
  },
  {
    name: 'Marvin Hiney',
    type: 'Advanced Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '05:20 pm'
  },
  {
    name: 'Annette Glash',
    type: 'Basic Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '07:00 am'
  },
  {
    name: 'Annette Glash',
    type: 'Basic Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '04:00 pm'
  },
  {
    name: 'Annette Glash',
    type: 'Basic Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '07:00 am'
  },
  {
    name: 'Annette Glash',
    type: 'Basic Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '07:00 am'
  },
  {
    name: 'Annette Glash',
    type: 'Basic Search',
    ip_address: '123.971.982.98',
    date: '28/08/2023',
    time: '07:00 am'
  }
]

export const mockAdminBulkUploadData = [
  {
    id: 1,
    Entity: 'Pamfilova Ella Aleksandrovna',
    Author: 'Claire',
    Type: 'Person',
    Status: 'Verified',
    TotalViews: '1129',
    Uploaded: '30/08/2023'
  },
  {
    id: 2,
    Entity: 'Pamfilova Ella Aleksandrovna',
    Author: 'Claire',
    Type: 'Person',
    Status: 'Verified',
    TotalViews: '1129',
    Uploaded: '30/08/2023'
  },
  {
    id: 3,
    Entity: 'Pamfilova Ella Aleksandrovna',
    Author: 'Claire',
    Type: 'Bank Account',
    Status: 'Unverified',
    TotalViews: '1129',
    Uploaded: '30/08/2023'
  },
  {
    id: 4,
    Entity: 'Pamfilova Ella Aleksandrovna',
    Author: 'Claire',
    Type: 'Companies',
    Status: 'Incorrect',
    TotalViews: '1129',
    Uploaded: '30/08/2023'
  },
  {
    id: 5,
    Entity: 'Pamfilova Ella Aleksandrovna',
    Author: 'Claire',
    Type: 'Crypto Wallet',
    Status: 'Incorrect',
    TotalViews: '1129',
    Uploaded: '30/08/2023'
  },
  {
    id: 6,
    Entity: 'Pamfilova Ella Aleksandrovna',
    Author: 'Claire',
    Type: 'Bank Account',
    Status: 'Unverified',
    TotalViews: '1129',
    Uploaded: '30/08/2023'
  }
]

export const mockCountryMultiFilterEditor = ['country', 'nationality', 'birthCountry', 'birthPlace']

export const mockAdminBulkUploadDataStatus = [
  'Verified', 'Unverified', 'Incorrect'
]

export const AdminEntityTypeArray = ['Person', 'Airplane', 'Address', 'BankAccount', 'Company', 'CryptoWallet', 'LegalEntity', 'Organization', 'Security', 'Vessel']

export const AdminEditPropertyArray = [
  {
    Person: ['nationality', 'createdAt', 'email', 'middleName', 'deathDate', 'website', 'idNumber', 'birthPlace', 'icijId', 'registrationNumber', 'birthCountry', 'gender', 'birthDate', 'modifiedAt', 'motherName', 'ogrnCode', 'sourceUrl', 'fatherName', 'country', 'lastName', 'political', 'taxNumber', 'ethnicity', 'legalForm', 'alias', 'summary', 'keywords', 'phone', 'publisher', 'nameSuffix', 'education', 'proof', 'notes', 'status', 'passportNumber', 'weakAlias', 'name', 'secondName', 'innCode', 'leiCode', 'wikidataId', 'religion', 'address', 'firstName', 'previousName', 'position'],
    Airplane: ['address', 'sourceUrl', 'addressEntity', 'model', 'country', 'registrationNumber', 'serialNumber', 'name', 'buildDate'],
    Address: ['region', 'street', 'state', 'summary', 'full', 'remarks', 'postalCode', 'country', 'city', 'postOfficeBox'],
    // Associate: ['startDate', 'endDate', 'modifiedAt', 'associate', 'person', 'relationship'],
    BankAccount: ['iban'],
    Company: ['ogrnCode', 'notes', 'status', 'alias', 'keywords', 'publisher', 'kppCode', 'opencorporatesUrl', 'previousName', 'addressEntity', 'address', 'phone', 'createdAt', 'registrationNumber', 'website', 'classification', 'proof', 'innCode', 'weakAlias', 'name', 'leiCode', 'summary', 'jurisdiction', 'incorporationDate', 'swiftBic', 'dissolutionDate', 'okpoCode', 'bikCode', 'mainCountry', 'dunsCode', 'icijId', 'email', 'idNumber', 'vatCode', 'sourceUrl', 'sector', 'topics', 'country', 'legalForm', 'taxNumber', 'modifiedAt', 'program'],
    CryptoWallet: ['amountUsd', 'modifiedAt', 'alias', 'balance', 'publicKey', 'currency', 'holder', 'createdAt'],
    // Directorship: ['publisher', 'summary', 'status', 'startDate', 'organization', 'modifiedAt', 'director', 'role', 'endDate'],
    // Employment: ['date', 'endDate', 'role', 'modifiedAt', 'summary', 'startDate', 'employer', 'employee'],
    // Family: ['startDate', 'relative', 'endDate', 'modifiedAt', 'relationship', 'person'],
    // Identification: ['country', 'type', 'startDate', 'number', 'summary', 'endDate', 'holder', 'authority', 'namesMentioned'],
    LegalEntity: ['phone', 'sourceUrl', 'address', 'addressEntity', 'country', 'legalForm', 'createdAt', 'registrationNumber', 'name', 'website', 'innCode', 'modifiedAt', 'previousName', 'incorporationDate', 'mainCountry', 'notes', 'status', 'icijId', 'email', 'alias', 'publisher'],
    // Membership: ['date', 'role', 'summary', 'endDate', 'modifiedAt', 'organization', 'startDate', 'member'],
    // Occupancy: ['startDate', 'description', 'post', 'status', 'holder', 'endDate'],
    Organization: ['createdAt', 'registrationNumber', 'email', 'icijId', 'dunsCode', 'idNumber', 'okpoCode', 'dissolutionDate', 'modifiedAt', 'ogrnCode', 'sourceUrl', 'vatCode', 'country', 'legalForm', 'sector', 'taxNumber', 'topics', 'alias', 'summary', 'publisher', 'keywords', 'opencorporatesUrl', 'phone', 'proof', 'notes', 'status', 'weakAlias', 'name', 'leiCode', 'innCode', 'jurisdiction', 'swiftBic', 'incorporationDate', 'wikidataId', 'address', 'previousName', 'addressEntity', 'website'],
    // Ownership: ['status', 'modifiedAt', 'date', 'role', 'sharesValue', 'percentage', 'recordId', 'sharesCount', 'sharesCurrency', 'startDate', 'publisher', 'asset', 'summary', 'owner', 'endDate'],
    // Passport: ['type', 'startDate', 'number', 'summary', 'holder', 'endDate', 'authority', 'country'],
    // Representation: ['publisher', 'endDate', 'role', 'summary', 'client', 'startDate', 'status', 'agent'],
    // Sanction: ['date', 'provisions', 'unscId', 'entity', 'program', 'authorityId', 'modifiedAt', 'recordId', 'country', 'authority', 'reason', 'sourceUrl', 'listingDate', 'publisher', 'endDate', 'summary', 'duration', 'startDate', 'status'],
    Security: ['country', 'classification', 'type', 'maturityDate', 'currency', 'amount', 'ticker', 'name', 'registrationNumber', 'isin', 'issuer', 'issueDate', 'createdAt', 'sourceUrl'],
    // UnknownLink: ['endDate', 'publisher', 'summary', 'status', 'modifiedAt', 'object', 'subject', 'startDate', 'role'],
    Vessel: ['tonnage', 'callSign', 'pastFlags', 'name', 'modifiedAt', 'buildDate', 'country', 'createdAt', 'registrationNumber', 'sourceUrl', 'grossRegisteredTonnage', 'imoNumber', 'address', 'proof', 'type', 'alias', 'notes', 'flag', 'mmsi']
  }
]
