export const nameObject = [
  {
    name: 'Name',
    birthDate: 'Birth date',
    country: 'Country',
    legalForm: 'Legal form',
    nationality: 'Nationality',
    status: 'Status',
    address: 'Address',
    addressEntity: 'Entity address',
    agencyClient: 'Clients',
    agentRepresentation: 'Agents Representation',
    alephUrl: 'Aleph URL',
    alias: 'Other name',
    associates: 'Associates',
    associations: 'Associations',
    authoredAssessments: 'Assessments authored',
    birthCountry: 'Country of birth',
    birthPlace: 'Place of birth',
    bvdId: 'Bureau van Dijk ID',
    callForTenders: 'Call For Tenders',
    callsMade: 'Calls made',
    callsReceived: 'Calls received',
    candidateSimilars: 'Similar to this',
    classification: 'Classification',
    contractAuthority: 'Contracts issued',
    contractAwardSupplier: 'Contracts awarded',
    courtCase: 'Court cases',
    createdAt: 'Created at',
    cryptoWallets: 'Cryptocurrency wallets',
    deathDate: 'Death date',
    debtCreditor: 'Credits',
    debtDebtor: 'Debts',
    delegatedCallForTenders: 'Delegated call for tenders',
    description: 'Description',
    directorshipDirector: 'Directorships',
    dissolutionDate: 'Dissolution date',
    documentedBy: 'Documents',
    dunsCode: 'D-U-N-S',
    economicActivityDeclarant: 'Customs declarations',
    economicActivityHolder: 'Customs declarations facilitated',
    economicActivityReceiver: 'Goods received',
    economicActivitySender: 'Goods originated',
    education: 'Education',
    email: 'E-Mail',
    emailsReceived: 'E-Mails received',
    emailsSent: 'E-Mails sent',
    employers: 'Employers',
    ethnicity: 'Ethnicity',
    eventsInvolved: 'Events',
    eventsOrganized: 'Organized events',
    familyPerson: 'Family members',
    familyRelative: 'Relatives',
    fatherName: 'Patronymic',
    firstName: 'First name',
    gender: 'Gender',
    icijId: 'ICIJ ID',
    identification: 'Identifications',
    idNumber: 'ID',
    images: 'Images',
    incorporationDate: 'Incorporation date',
    indexText: 'Index text',
    innCode: 'INN',
    jurisdiction: 'Jurisdiction',
    keywords: 'Keywords',
    lastName: 'Last name',
    leiCode: 'LEI',
    mainCountry: 'Country of origin',
    matchSimilars: 'Similar',
    membershipMember: 'Memberships',
    mentionedBy: 'Mentions',
    messagesReceived: 'Messages received',
    messagesSent: 'Messages sent',
    middleName: 'Middle name',
    modifiedAt: 'Modified on',
    motherName: 'Matronymic',
    nameSuffix: 'Name suffix',
    noteEntities: 'Notes',
    notes: 'Notes text',
    ogrnCode: 'OGRN',
    okpoCode: 'OKPO',
    opencorporatesUrl: 'OpenCorporates URL',
    operatedVehicles: 'Vehicles operated',
    ownedVehicles: 'Vehicles owned',
    ownershipOwner: 'Assets and shares',
    parent: 'Parent company',
    passportNumber: 'Passport number',
    paymentBeneficiary: 'Payments received',
    paymentPayer: 'Payments made',
    phone: 'Phone',
    political: 'Political association',
    position: 'Position',
    positionOccupancies: 'Positions held',
    posts: 'Posts held',
    predecessors: 'Predecessors',
    previousName: 'Previous name',
    program: 'Program',
    projectParticipation: 'Projects',
    proof: 'Source document',
    publisher: 'Publishing source',
    publisherUrl: 'Publishing source URL',
    registrationNumber: 'Registration number',
    religion: 'Religion',
    retrievedAt: 'Retrieved on',
    sanctions: 'Sanctions',
    secondName: 'Second name',
    sector: 'Sector',
    securities: 'Issued securities',
    sourceUrl: 'Source link',
    subsidiaries: 'Subsidiaries',
    successors: 'Successors',
    summary: 'Summary',
    swiftBic: 'SWIFT/BIC',
    taxNumber: 'Tax Number',
    taxRolls: 'Tax rolls',
    taxStatus: 'Tax status',
    title: 'Title',
    topics: 'Topics',
    unknownLinkFrom: 'Linked from',
    unknownLinkTo: 'Linked to',
    userAccounts: 'User accounts',
    vatCode: 'V.A.T. Identifier',
    weakAlias: 'Weak alias',
    website: 'Website',
    wikidataId: 'Wikidata ID',
    wikipediaUrl: 'Wikipedia',
    city: 'City',
    full: 'Full address',
    street: 'Street address',
    googlePlaceId: 'Google Places ID',
    latitude: 'Latitude',
    longitude: 'Longitude',
    osmId: 'OpenStreetmap Place ID',
    postalCode: 'Postal code',
    postOfficeBox: 'PO Box',
    region: 'Region',
    remarks: 'Remarks',
    state: 'State',
    street2: 'Street address (ctd.)',
    things: 'Located there',
    tripsDeparting: 'Trips departing',
    tripsIncoming: 'Trips incoming',
    flag: 'Flag',
    imoNumber: 'IMO Number',
    callSign: 'Call Sign',
    crsNumber: 'CRS Number',
    grossRegisteredTonnage: 'Gross Registered Tonnage',
    mmsi: 'MMSI identifier',
    nameChangeDate: 'Date of Name Change',
    navigationArea: 'Navigation Area',
    pastFlags: 'Past Flags',
    pastTypes: 'Past Types',
    registrationPort: 'Port of Registration',
    tonnage: 'Tonnage',
    owner: 'Owner LegalEntity',
    type: 'Type',
    buildDate: 'Build Date',
    declaredCustoms: 'Customs declarations',
    deregistrationDate: 'De-registration Date',
    model: 'Model',
    operator: 'Operator',
    registrationDate: 'Registration Date',
    tripsInvolved: 'Trips',
    icaoCode: 'ICAO aircraft type designator',
    manufacturer: 'Manufacturer',
    serialNumber: 'Serial Number',
    ownershipAsset: 'Owners',
    amount: 'Amount',
    amountEur: 'Amount in EUR',
    amountUsd: 'Amount in USD',
    currency: 'Currency',
    author: 'Author',
    publishDate: 'Date of publishing',
    assessmentId: 'Assessment ID',
    associate: 'Associate',
    person: 'Person',
    relationship: 'Relationship',
    accountNumber: 'Account number',
    bankName: 'Bank name',
    accountType: 'Account type',
    balance: 'Balance',
    balanceDate: 'Balance date',
    bank: 'Bank',
    bankAddress: 'Bank address',
    bic: 'Bank Identifier Code',
    closingDate: 'Closing date',
    contractBankAccount: 'Customs declarations',
    foreignBankAccount: 'Customs declarations (as foreign bank)',
    iban: 'IBAN',
    maxBalance: 'Maximum balance',
    maxBalanceDate: 'Maximum balance date',
    openingDate: 'Opening date',
    paymentBeneficiaryAccount: 'Payments received',
    paymentPayerAccount: 'Payments made',
    rubBankAccount: 'Customs declarations (as rouble bank)',
    caller: 'Caller',
    callerNumber: "Caller's Number",
    receiver: 'Receiver',
    receiverNumber: "Receiver's Number",
    duration: 'Duration',
    bikCode: 'BIK',
    caemCode: 'COD CAEM',
    capital: 'Capital',
    cikCode: 'SEC Central Index Key',
    coatoCode: 'COATO / SOATO / OKATO',
    fnsCode: 'Federal tax service code',
    fssCode: 'FSS',
    ibcRuc: 'ibcRUC',
    ipoCode: 'IPO',
    irsCode: 'IRS Number',
    isinCode: 'ISIN',
    jibCode: 'JIB',
    kppCode: 'KPP',
    mbsCode: 'MBS',
    okopfCode: 'OKOPF',
    oksmCode: 'OKSM',
    okvedCode: 'OKVED(2) Classifier',
    permId: 'PermID',
    pfrNumber: 'PFR Number',
    ricCode: 'Reuters Instrument Code',
    ticker: 'Stock ticker symbol',
    voenCode: 'VOEN',
    publicKey: 'Address',
    creationDate: 'Creation date',
    currencySymbol: 'Currency short code',
    holder: 'Wallet holder',
    mangingExchange: 'Managing exchange',
    privateKey: 'Private key',
    debtor: 'Debtor',
    creditor: 'Creditor',
    director: 'Director',
    organization: 'Organization',
    date: 'Date',
    endDate: 'End date',
    namesMentioned: 'Detected names',
    recordId: 'Record ID',
    role: 'Role',
    secretary: 'Secretary',
    startDate: 'Start date',
    employee: 'Employee',
    employer: 'Employer',
    relative: 'Relative',
    number: 'Document number',
    authority: 'Authority',
    member: 'Member',
    post: 'Position occupied',
    bankAccounts: 'Bank accounts',
    directorshipOrganization: 'Directors',
    employees: 'Employees',
    membershipOrganization: 'Members',
    positions: 'Positions',
    object: 'Object',
    subject: 'Subject',
    asset: 'Asset',
    percentage: 'Percentage held',
    legalBasis: 'Legal basis',
    publishingSource: 'Publishing source',
    ownershipType: 'Type of ownership',
    sharesCount: 'Number of shares',
    sharesCurrency: 'Currency of shares',
    sharesType: 'Type of shares',
    sharesValue: 'Value of shares',
    givenName: 'Given name',
    personalNumber: 'Personal number',
    surname: 'Surname',
    agent: 'Agent',
    client: 'Client',
    entity: 'Entity',
    authorityId: 'Authority-issued identifier',
    listingDate: 'Listing date',
    provisions: 'Scope of sanctions',
    reason: 'Reason',
    unscId: 'UN SC identifier',
    isin: 'ISIN',
    issuer: 'Issuer',
    collateral: 'Collateral',
    figiCode: 'Financial Instrument Global Identifier',
    issueDate: 'Date issued',
    maturityDate: 'Maturity date',
    last_seen: 'Last seen',
    last_change: 'Last change',
    first_seen: 'First seen'
  }
]
